#!/usr/bin/env bash
# Turns the OFFSITE_CLOUD_* slot in .env into pgBackRest's repo2 (dev-plan
# 9.2 step 1). Sourced by both containers that speak pgBackRest: the `db`
# container, whose archive_command pushes WAL, and the `pgbackrest` sidecar,
# which takes the backups.
#
# Why a config file and not environment variables. pgBackRest refuses an
# environment variable that is defined but empty:
#
#   ERROR: [032]: environment variable 'repo2-type' must have a value
#
# Compose has no way to leave a variable out, so passing PGBACKREST_REPO2_*
# through would break every instance that has no offsite target, including
# archive_command, which would then hold WAL until the disk filled. A file
# that is simply absent when the slot is empty has no such failure mode.
#
# The file goes in pgBackRest's own include directory (config-include-path,
# /etc/pgbackrest/conf.d by default). A drop-in may add options but must not
# repeat one from pgbackrest.conf: pgBackRest refuses with "option ... cannot
# be set multiple times". Everything written here is repo2-only or absent
# from the main file, and that is a rule for anyone editing either.

OFFSITE_CONF_DIR="${OFFSITE_CONF_DIR:-/etc/pgbackrest/conf.d}"
OFFSITE_CONF="$OFFSITE_CONF_DIR/repo2-cloud.conf"

# Prints why the slot cannot be used, or nothing when it is usable. An empty
# type means "no offsite target", which is not an error.
offsite_cloud_problem() {
  [ -z "${OFFSITE_CLOUD_TYPE:-}" ] && return 1
  local missing=()
  [ -z "${OFFSITE_CLOUD_BUCKET:-}" ]     && missing+=(OFFSITE_CLOUD_BUCKET)
  [ -z "${OFFSITE_CLOUD_ENDPOINT:-}" ]   && missing+=(OFFSITE_CLOUD_ENDPOINT)
  [ -z "${OFFSITE_CLOUD_KEY:-}" ]        && missing+=(OFFSITE_CLOUD_KEY)
  [ -z "${OFFSITE_CLOUD_SECRET:-}" ]     && missing+=(OFFSITE_CLOUD_SECRET)
  # Its own passphrase, never the local one: decision 4, so that a leaked
  # remote passphrase cannot read the local repository. The sidecar refuses
  # the slot rather than falling back, which is the whole point of the rule.
  [ -z "${OFFSITE_CLOUD_PASSPHRASE:-}" ] && missing+=(OFFSITE_CLOUD_PASSPHRASE)
  if [ ${#missing[@]} -gt 0 ]; then
    echo "OFFSITE_CLOUD_TYPE is set but ${missing[*]} $([ ${#missing[@]} -eq 1 ] && echo is || echo are) empty"
    return 0
  fi
  case "${OFFSITE_CLOUD_TYPE}" in
    s3|b2) ;;
    *) echo "OFFSITE_CLOUD_TYPE '${OFFSITE_CLOUD_TYPE}' is not one of: s3, b2"; return 0 ;;
  esac
  return 1
}

offsite_cloud_enabled() {
  [ -n "${OFFSITE_CLOUD_TYPE:-}" ] && ! offsite_cloud_problem >/dev/null
}

# Writes the drop-in, or removes it when the slot is empty or unusable. Never
# leaves a half-written file behind: a broken repo2 would stop archive_command
# and, with it, the database's ability to recycle WAL.
offsite_write_conf() {
  local problem
  mkdir -p "$OFFSITE_CONF_DIR" 2>/dev/null

  if [ -z "${OFFSITE_CLOUD_TYPE:-}" ]; then
    rm -f "$OFFSITE_CONF"
    echo "offsite: no cloud target configured"
    return 0
  fi
  if problem="$(offsite_cloud_problem)"; then
    rm -f "$OFFSITE_CONF"
    echo "offsite: DISABLED, $problem"
    return 1
  fi

  # B2's S3 endpoint is an ordinary S3 endpoint; the type only picks defaults.
  local uri_style="${OFFSITE_CLOUD_URI_STYLE:-host}"
  local region="${OFFSITE_CLOUD_REGION:-us-east-1}"
  local repo_path="${OFFSITE_CLOUD_PATH:-/tesria}"
  local retention="${OFFSITE_CLOUD_RETENTION_FULL:-4}"
  local queue_max="${OFFSITE_ARCHIVE_QUEUE_MAX:-16GiB}"
  local tmp="$OFFSITE_CONF.tmp.$$"

  {
    echo "# Generated by deploy/pgbackrest/offsite.sh from the OFFSITE_CLOUD_*"
    echo "# slot in .env. Edits here are overwritten on the next container start."
    echo "[global]"
    echo "repo2-type=s3"
    echo "repo2-path=${repo_path}"
    echo "repo2-s3-bucket=${OFFSITE_CLOUD_BUCKET}"
    echo "repo2-s3-endpoint=${OFFSITE_CLOUD_ENDPOINT}"
    echo "repo2-s3-region=${region}"
    echo "repo2-s3-uri-style=${uri_style}"
    echo "repo2-s3-key=${OFFSITE_CLOUD_KEY}"
    echo "repo2-s3-key-secret=${OFFSITE_CLOUD_SECRET}"
    [ "${OFFSITE_CLOUD_VERIFY_TLS:-y}" = "n" ] && echo "repo2-storage-verify-tls=n"
    echo "repo2-cipher-type=aes-256-cbc"
    echo "repo2-cipher-pass=${OFFSITE_CLOUD_PASSPHRASE}"
    # Fewer, larger objects: object stores charge and rate-limit per request.
    echo "repo2-bundle=y"
    # This repository's own retention (decision 5). repo1's lives in
    # pgbackrest.conf and is driven by the admin page instead.
    echo "repo2-retention-full=${retention}"
    # The safety valve, and the reason 2.59 is the floor: past this much
    # unarchived WAL, pgBackRest tells Postgres the segment is archived and
    # DROPS it, so a dead remote costs point-in-time recovery from that
    # moment rather than the whole database to a full disk. Set only when an
    # offsite repository exists, because that is when the risk appears.
    echo "archive-push-queue-max=${queue_max}"
  } > "$tmp" || { rm -f "$tmp"; echo "offsite: could not write $OFFSITE_CONF"; return 1; }

  # The file holds a storage key and a passphrase. pgBackRest runs as
  # postgres in both containers and needs to read it; nobody else should.
  chmod 0640 "$tmp" 2>/dev/null
  chown root:postgres "$tmp" 2>/dev/null
  mv -f "$tmp" "$OFFSITE_CONF" || { rm -f "$tmp"; return 1; }

  echo "offsite: cloud target enabled, ${OFFSITE_CLOUD_TYPE} bucket ${OFFSITE_CLOUD_BUCKET}${repo_path}"
  return 0
}

# A short, stable fingerprint of a secret, for showing on a screen. Never the
# value: the app must have no way to read one back (9.2's whole reason for
# keeping these in .env). Same shape as the avatar hashes: SHA-256, 16 hex.
offsite_fingerprint() {
  [ -z "${1:-}" ] && { echo ""; return; }
  printf '%s' "$1" | sha256sum | cut -c1-16
}
