using System.Security.Cryptography;
using SkiaSharp;

namespace Tesria.Api.Infrastructure.Storage;

/// <summary>What a stored image belongs to. Determines its key namespace.</summary>
public enum ProfileMediaKind
{
    Avatar = 0,
    SpaceIcon = 1,
}

/// <summary>The stored result: the storage key, and a hash for cache busting.</summary>
public record StoredMedia(string StorageKey, string ContentHash);

public sealed class ProfileMediaException(string message) : Exception(message);

public interface IProfileMediaService
{
    /// <summary>
    /// Validates, re-encodes and stores an uploaded image, replacing whatever
    /// was previously stored for this owner. Throws
    /// <see cref="ProfileMediaException"/> with a caller-safe message when the
    /// upload is rejected.
    /// </summary>
    Task<StoredMedia> StoreAsync(ProfileMediaKind kind, Guid ownerId, Stream content, CancellationToken ct = default);

    /// <summary>The stored bytes, or null if there are none.</summary>
    Stream? OpenRead(string storageKey);

    void Delete(string storageKey);
}

/// <summary>
/// Avatars and space icons, stored through the existing
/// <see cref="IAttachmentStorage"/> under their own key namespaces rather than
/// via a second storage abstraction — so the S3 implementation that interface
/// reserves a slot for covers these too, for free.
///
/// Every upload is re-encoded rather than stored as received. That is the
/// security control, not a convenience:
///
/// * it strips EXIF, which routinely carries GPS coordinates — a real leak for
///   a photo someone uses as an avatar;
/// * it defeats polyglot files (a valid PNG that is also a valid HTML or ZIP
///   document), because the bytes written are ones this process produced;
/// * it bounds decoded dimensions, so a "decompression bomb" cannot be stored
///   and then re-served to every viewer.
///
/// SVG is rejected outright. It is a script-bearing document format, and there
/// is no reason to accept one for a 256px square. The prebuilt avatars in
/// dev-plan 1.2 are SVG, but those are generated by this application, never
/// uploaded.
/// </summary>
public sealed class ProfileMediaService(IAttachmentStorage storage) : IProfileMediaService
{
    /// <summary>Stored edge length. Avatars render at 20–40px, so 256 covers retina and to spare.</summary>
    public const int OutputSize = 256;

    /// <summary>Upload cap, before decoding.</summary>
    public const long MaxBytes = 1024 * 1024;

    /// <summary>
    /// Cap on decoded pixels (~40 megapixels). A few hundred KB of PNG can
    /// decode to gigabytes of bitmap; this is checked from the header before
    /// any pixel buffer is allocated.
    /// </summary>
    private const long MaxDecodedPixels = 40_000_000;

    public async Task<StoredMedia> StoreAsync(
        ProfileMediaKind kind, Guid ownerId, Stream content, CancellationToken ct = default)
    {
        // Buffer with a hard ceiling: never read an unbounded stream into memory
        // just to discover afterwards that it was too big.
        using var buffer = new MemoryStream();
        var copied = await CopyWithLimitAsync(content, buffer, MaxBytes, ct);
        if (copied is null)
            throw new ProfileMediaException($"Image must be {MaxBytes / 1024} KB or smaller.");
        if (buffer.Length == 0)
            throw new ProfileMediaException("Image is empty.");

        buffer.Position = 0;
        var bytes = buffer.ToArray();

        if (LooksLikeSvg(bytes))
            throw new ProfileMediaException("SVG images are not accepted. Use PNG, JPEG or WebP.");

        var encoded = ReencodeSquare(bytes);

        var key = Key(kind, ownerId);
        using var output = new MemoryStream(encoded);
        await storage.SaveAsync(key, output, ct);

        return new StoredMedia(key, Hash(encoded));
    }

    public Stream? OpenRead(string storageKey) => storage.OpenRead(storageKey);

    public void Delete(string storageKey) => storage.Delete(storageKey);

    /// <summary>
    /// Deterministic per owner, so a replacement overwrites rather than
    /// accumulating orphans. Cache busting is the content hash on the URL, not
    /// a unique key — see the media endpoints.
    /// </summary>
    private static string Key(ProfileMediaKind kind, Guid ownerId) =>
        kind switch
        {
            ProfileMediaKind.Avatar => $"avatars/{ownerId}.webp",
            ProfileMediaKind.SpaceIcon => $"space-icons/{ownerId}.webp",
            _ => throw new ArgumentOutOfRangeException(nameof(kind)),
        };

    /// <summary>Copies up to <paramref name="limit"/> bytes; null if the source exceeds it.</summary>
    private static async Task<long?> CopyWithLimitAsync(
        Stream source, Stream destination, long limit, CancellationToken ct)
    {
        var chunk = new byte[81920];
        long total = 0;
        int read;
        while ((read = await source.ReadAsync(chunk, ct)) > 0)
        {
            total += read;
            if (total > limit) return null;
            await destination.WriteAsync(chunk.AsMemory(0, read), ct);
        }
        return total;
    }

    /// <summary>
    /// Detects SVG before decoding. Sniffs content rather than trusting the
    /// client's declared content type, which is attacker-controlled — the
    /// leading bytes may be an XML declaration, a comment, or the tag itself.
    /// </summary>
    private static bool LooksLikeSvg(byte[] bytes)
    {
        var probe = System.Text.Encoding.UTF8.GetString(
            bytes, 0, Math.Min(bytes.Length, 512)).TrimStart('﻿', ' ', '\t', '\r', '\n');
        return probe.StartsWith("<?xml", StringComparison.OrdinalIgnoreCase)
            || probe.StartsWith("<svg", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Decodes, centre-crops to a square, scales to <see cref="OutputSize"/> and
    /// re-encodes as WebP. The output format is fixed rather than mirroring the
    /// input, so exactly one content type is ever served.
    /// </summary>
    private static byte[] ReencodeSquare(byte[] bytes)
    {
        using var data = SKData.CreateCopy(bytes);

        // Read dimensions from the header first: this allocates no pixel buffer,
        // so an oversized image is refused before it can be decoded.
        using (var codec = SKCodec.Create(data))
        {
            if (codec is null)
                throw new ProfileMediaException("Unrecognised image format. Use PNG, JPEG or WebP.");
            var info = codec.Info;
            if ((long)info.Width * info.Height > MaxDecodedPixels)
                throw new ProfileMediaException("Image dimensions are too large.");
        }

        using var source = SKBitmap.Decode(data)
            ?? throw new ProfileMediaException("Image could not be decoded. Use PNG, JPEG or WebP.");

        // Centre crop to a square so the scale never distorts the aspect ratio.
        var edge = Math.Min(source.Width, source.Height);
        var cropRect = SKRectI.Create(
            (source.Width - edge) / 2, (source.Height - edge) / 2, edge, edge);

        using var square = new SKBitmap(edge, edge);
        if (!source.ExtractSubset(square, cropRect))
            throw new ProfileMediaException("Image could not be processed.");

        var target = new SKImageInfo(OutputSize, OutputSize, SKColorType.Rgba8888, SKAlphaType.Premul);
        using var resized = square.Resize(target, new SKSamplingOptions(SKFilterMode.Linear, SKMipmapMode.Linear))
            ?? throw new ProfileMediaException("Image could not be resized.");

        using var image = SKImage.FromBitmap(resized);
        using var output = image.Encode(SKEncodedImageFormat.Webp, 90)
            ?? throw new ProfileMediaException("Image could not be encoded.");
        return output.ToArray();
    }

    /// <summary>Short content hash, used as the cache-busting query value on media URLs.</summary>
    private static string Hash(byte[] content) =>
        Convert.ToHexStringLower(SHA256.HashData(content))[..16];
}
